### ISSUE TITLE
About http/2 in fe3.delivery.mp.microsoft.com

### ISSUE THREAD

**Issue by cjw1115** [StoreDev/StoreLib#13] opened 2021-08-04 17:54 UTC
hello! This is a very amazing project. Appreciate it.

I tried to catch the Microsoft store app install request with Fiddler, BurpSuite...to many tools.

But I always got errors about fe3cr.delivery.mp.microsoft.com, it's a http/2 connection, I tried to set system proxy to get the request. But however, if I try to catch it, it always failed, it only succeed when I remove the proxy.

So I want to know how do you resolve this problem? could you help me.
Thanks.

**Comment by TitleOS** [comment] 2021-09-02 16:25
As this isn't an issue with StoreLib, I will be closing it. However, the problem is caused by Windows performing cert pinning on certain store related domains such as FE3. The workaround requires patching certain Windows system dlls.

**Closed as completed by TitleOS** 2021-09-02 16:25 UTC
